In [1]:
import os
import pandas as pd

os.chdir("../..")

In [2]:
train = pd.read_csv("results/bert_finetuned/bert_for_score_prediction_train.csv", index_col=0).sort_index()
train2 = pd.read_csv("results/bert_finetuned/bert_for_risk_level_classification_train.csv", index_col=0).sort_index()
train["esg_risk_level_pred"] = train2["esg_risk_level_pred"]
train

,symbol,year,quarter,transcript_esg,esg_score,esg_risk_level,esg_score_pred,esg_risk_level_pred
0,A,2022,1,thank emily welcome everyone agilents conferen...,15.0,Low,14.872769,Low
1,A,2022,3,thank hannah welcome everyone agilents confere...,15.0,Low,21.983328,Low
2,AAPL,2022,1,good day welcome apple q fy earnings conferenc...,17.0,Low,17.280869,Low
3,AAPL,2022,2,good day welcome apple q fy earnings conferenc...,17.0,Low,17.340609,Low
4,AAPL,2022,3,good day welcome apple q fy earnings conferenc...,17.0,Low,15.467926,Low
...,...,...,...,...,...,...,...,...
542,WMT,2023,3,followed questionandanswer session turn call d...,25.0,Medium,26.104294,Medium
543,YUM,2022,1,welcome q yum brand earnings conference call n...,21.0,Medium,21.570585,Medium
544,YUM,2022,2,get started would like remind conference call ...,21.0,Medium,20.235195,Medium
545,ZTS,2022,1,thank operator good morning everyone welcome z...,18.0,Low,17.897696,Low
546,ZTS,2022,2,thank good morning everyone welcome zoetis sec...,18.0,Low,18.339306,Low

In [3]:
test = pd.read_csv("results/bert_finetuned/bert_for_score_prediction_test.csv", index_col=0).sort_index()
test2 = pd.read_csv("results/bert_finetuned/bert_for_risk_level_classification_test.csv", index_col=0).sort_index()
test["esg_risk_level_pred"] = test2["esg_risk_level_pred"]
test

,symbol,year,quarter,transcript_esg,esg_score,esg_risk_level,esg_score_pred,esg_risk_level_pred
0,ADP,2022,1,call reference nongaap financial measures beli...,14.0,Low,15.311826,Low
1,ADP,2022,1,call reference nongaap financial measures beli...,14.0,Low,15.311826,Low
2,ADSK,2022,1,addition replay call available autodeskcominve...,16.0,Negligible,15.134399,Low
3,ADSK,2022,3,addition replay call available autodeskcominve...,16.0,Negligible,18.173985,Low
4,ADSK,2022,4,addition replay call available autodeskcominve...,16.0,Negligible,15.513392,Low
...,...,...,...,...,...,...,...,...
133,VRTX,2022,2,reshma kewalramani vertexs ceo president stuar...,23.0,Medium,25.738070,Medium
134,VRTX,2022,3,reshma kewalramani vertexs ceo president stuar...,23.0,Medium,25.967310,Medium
135,XRAY,2022,1,begin let start im excited took role interim c...,16.0,Negligible,22.533587,Medium
136,XYL,2022,2,good morning everyone welcome xylems second qu...,16.0,Negligible,20.174566,Medium
137,XYL,2022,2,good morning everyone welcome xylems second qu...,16.0,Negligible,20.174566,Medium

In [4]:
combined = pd.concat([train, test], ignore_index=True)
combined

,symbol,year,quarter,transcript_esg,esg_score,esg_risk_level,esg_score_pred,esg_risk_level_pred
0,A,2022,1,thank emily welcome everyone agilents conferen...,15.0,Low,14.872769,Low
1,A,2022,3,thank hannah welcome everyone agilents confere...,15.0,Low,21.983328,Low
2,AAPL,2022,1,good day welcome apple q fy earnings conferenc...,17.0,Low,17.280869,Low
3,AAPL,2022,2,good day welcome apple q fy earnings conferenc...,17.0,Low,17.340609,Low
4,AAPL,2022,3,good day welcome apple q fy earnings conferenc...,17.0,Low,15.467926,Low
...,...,...,...,...,...,...,...,...
677,VRTX,2022,2,reshma kewalramani vertexs ceo president stuar...,23.0,Medium,25.738070,Medium
678,VRTX,2022,3,reshma kewalramani vertexs ceo president stuar...,23.0,Medium,25.967310,Medium
679,XRAY,2022,1,begin let start im excited took role interim c...,16.0,Negligible,22.533587,Medium
680,XYL,2022,2,good morning everyone welcome xylems second qu...,16.0,Negligible,20.174566,Medium
681,XYL,2022,2,good morning everyone welcome xylems second qu...,16.0,Negligible,20.174566,Medium

In [5]:
# combined.to_csv("data/predicted/combined_predictions.csv")